/* ============================================================================
 * tools/gen-cities.js — one-shot build script (NOT shipped, NOT run at runtime)
 * ----------------------------------------------------------------------------
 * Turns the GeoNames US dump into the compact cities-data.js the extension
 * ships. Source (CC-BY 4.0 — attribute in README):
 *   https://download.geonames.org/export/dump/US.zip   (US.txt inside)
 *
 * We chose GeoNames over the Census Gazetteer because the Census "places" file
 * EXCLUDES New England towns (they're county subdivisions, not places), so it
 * was missing the user's own area (e.g. Bedford, MA). GeoNames includes them
 * and uses common names (no "...Town city" suffixes).
 *
 * Usage:  node tools/gen-cities.js <path-to-US.txt> [out.js] [minPop]
 *
 * Output: cities-data.js setting `self.__ML_CITIES_TSV` to a newline-delimited
 * "city|ST|lat|lng" string. city is normalized IDENTICALLY to content.js's
 * normalizeCity() — keep the two in sync.
 *
 * GeoNames US.txt columns (tab-sep): 1 geonameid, 2 name, 3 asciiname,
 * 4 altnames, 5 lat, 6 lng, 7 feature_class, 8 feature_code, 9 country,
 * 10 cc2, 11 admin1_code (US = 2-letter state), ... 15 population, ...
 * ==========================================================================*/
"use strict";
const fs = require("fs");

const inPath = process.argv[2];
const outPath = process.argv[3] || "cities-data.js";
const MIN_POP = Number(process.argv[4] || 100);
if (!inPath) {
  console.error("usage: node tools/gen-cities.js <US.txt> [out.js] [minPop]");
  process.exit(1);
}

// MUST match content.js normalizeCity() exactly.
function normalizeCity(s) {
  return String(s)
    .toLowerCase()
    .trim()
    .replace(/\s+/g, " ")
    .replace(/^st\.?\s/, "saint ")
    .replace(/^ft\.?\s/, "fort ")
    .replace(/\./g, "");
}

const data = fs.readFileSync(inPath, "utf8");
// key -> { lat, lng, pop } keeping the highest-population entry per city|state.
const best = new Map();
let rows = 0;

let start = 0;
for (let nl = data.indexOf("\n"); nl !== -1; nl = data.indexOf("\n", start)) {
  const line = data.slice(start, nl);
  start = nl + 1;
  if (!line) continue;
  const c = line.split("\t");
  if (c.length < 15) continue;
  if (c[6] !== "P") continue; // populated places only
  const st = c[10].trim().toLowerCase();
  if (!/^[a-z]{2}$/.test(st)) continue; // 2-letter state/territory only
  const city = normalizeCity(c[2] || c[1]); // asciiname preferred
  if (!city) continue;
  const lat = Number(c[4]);
  const lng = Number(c[5]);
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) continue;
  const pop = Number(c[14]) || 0;
  rows++;
  const key = city + "|" + st;
  const prev = best.get(key);
  if (!prev || pop > prev.pop) best.set(key, { lat, lng, pop });
}

const out = [];
for (const [key, v] of best) {
  if (v.pop < MIN_POP) continue;
  out.push(key + "|" + v.lat.toFixed(4) + "|" + v.lng.toFixed(4));
}
out.sort();

const header =
  "/* Generated by tools/gen-cities.js from the GeoNames US dump (CC-BY 4.0,\n" +
  " * https://www.geonames.org/). Each line: city|ST|lat|lng (city pre-\n" +
  " * normalized to match content.js normalizeCity()). Regenerate; don't edit. */\n";
const body =
  header + "self.__ML_CITIES_TSV = " + JSON.stringify(out.join("\n")) + ";\n";
fs.writeFileSync(outPath, body);

console.error(
  `scanned ${rows} class-P rows; kept ${out.length} cities (pop>=${MIN_POP}); ` +
    `wrote ${outPath} (${(body.length / 1024).toFixed(0)} KB)`
);
